name: telegram-movie-bot
services:
  - name: bot
    git:
      repo: https://github.com/Farook13/bot
      branch: main
    ports:
      - port: 8000  # Optional, not needed for worker
    instance_types:
      - type: free  # Use Koyeb's free tier
    build:
      command: pip install -r requirements.txt
    run:
      command: python main.py
